# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
import pandas as pd 
import numpy as np

configfile:"config/config.yaml"
dataset = config['dataset']
metadata = pd.read_csv(config['metadata'], sep="\t")
samples = metadata['sampleID']
report: "report/workflow.rst"

include: "rules/common.smk"	
include: "rules/utilities.smk"
include: "rules/qc.smk"
include: "rules/alignment-variantcalling.smk"
include: "rules/analysis.smk"
include: "rules/bcl-convert.smk"
include: "rules/jupyter-book.smk"

rule all:
	input:
		# The first rule should define the default target files
		AmpSeekerOutputs,