# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
import pandas as pd 
import numpy as np

configfile:"config/config.yaml"
dataset = config['dataset']
metadata = pd.read_csv(config['metadata'], sep="\t")
samples = metadata['sampleID']
# sample_numbers = metadata['sampleID'].str.extract('(\\d+)$').astype(int)
reference_type = config['reference_type']
report: "report/workflow.rst"

include: "rules/common.smk"	
include: "rules/utilities.smk"
include: "rules/qc.smk"
include: "rules/alignment_variantcalling.smk"
include: "rules/analysis.smk"
include: "rules/bcl_convert.smk"

# containerized: "docker://chabbytmd1/ampseeker:1.0"

rule all:
	input:
		# The first rule should define the default target files
		AmpSeekerOutputs,