# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
dataset: "AgamDao"
metadata: "config/dummy_metadata.tsv"
present_samples:  "resources/present.samples.txt"

# Directory of Illumina Miseq Run
illumina_dir: /home/sanj/projects/AmpSeqVIGG2022/resources/220329_M05658_0010_000000000-K9TYL

# Genome fasta reference files 
ref:
  wholegenome: "resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa"
  amplicon: "resources/reference/AGAMP4_AGAMDAO_amplicons.fa"

# .bed file of target SNPs
bed:
  wholegenome: "resources/AgamDao_wholegenome_snptargets.bed"
  amplicon: "resources/AgamDao_amplicon_snptargets.bed"

